# Generated by Django 4.1.2 on 2025-02-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
