# Generated by Django 5.1.7 on 2025-03-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='service',
            field=models.CharField(choices=[('window_replacement', 'Window Replacement'), ('door_installation', 'Door Installation'), ('roof_repair', 'Roof Repair')], max_length=100),
        ),
    ]
