# Generated by Django 5.1.7 on 2025-03-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_order_customer_name_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Admin', 'Admin'), ('Sales', 'Sales'), ('Technician', 'Technician'), ('Manager', 'Manager')], default='Employee', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default-profile.png', upload_to='profile_pics/'),
        ),
    ]
