# Generated by Django 4.1.2 on 2025-03-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_role_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
