# Generated by Django 4.1.2 on 2025-03-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in-progress', 'In Progress')], default='in-progress', max_length=50),
        ),
    ]
