# Generated by Django 5.1.7 on 2025-04-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
