# Generated by Django 4.1.2 on 2025-03-16 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_lead_options_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
