# Generated by Django 5.1.7 on 2025-04-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_order_options_order_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='windowType',
            field=models.CharField(choices=[('double_hung', 'Double Hung'), ('casement', 'Casement'), ('sliding', 'Sliding'), ('picture', 'Picture'), ('custom', 'Custom')], max_length=50),
        ),
    ]
