# Generated by Django 5.1.7 on 2025-04-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_facebooklead'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooklead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='facebooklead',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facebooklead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
