# Generated by Django 5.1.7 on 2025-04-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(default='Ediomi Iyanam', max_length=100),
        ),
    ]
