# Generated by Django 5.1.7 on 2025-05-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_author_name_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Optional: Used for SEO and Google previews.', max_length=160),
        ),
    ]
