# Generated by Django 5.1.7 on 2025-05-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
