"""
Django settings for LPageToAdmin project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
import environ
import logging

logging.basicConfig(level=logging.DEBUG)


# ✅ Define BASE_DIR FIRST
BASE_DIR = Path(__file__).resolve().parent.parent

# ✅ Initialize environment variables
env = environ.Env()
env_file = os.path.join(BASE_DIR, ".env")

# ✅ Load .env file if it exists
if os.path.exists(env_file):
    env.read_env(env_file)


# Email Backend Settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True  # ✅ Keep TLS enabled
EMAIL_USE_SSL = False  # ❌ Must be False if TLS is True

EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")  # ✅ Load from .env
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")  # ✅ Load from .env
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "fallback-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"  # Ensures DEBUG is a boolean

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "windowgeniusai.herokuapp.com",
    "windowgeniusai-d6c9fb157af2.herokuapp.com",
    "www.windowgeniusai.com",
    "windowgeniusai.com",
    
]

# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",  # ✅ **THIS WAS MISSING!**
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app",
    "chatbot",
    "whitenoise.runserver_nostatic",
    "django_extensions",
    "csp",  # ✅ Enables Django CSP Middleware
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # ✅ MUST BE FIRST
    "django.middleware.security.SecurityMiddleware",  # ✅ Security comes first
    "whitenoise.middleware.WhiteNoiseMiddleware",  # ✅ Static file handling (best practice: after security)
    "django.contrib.sessions.middleware.SessionMiddleware",  # ✅ Manages sessions
    "django.middleware.common.CommonMiddleware",  # ✅ Enables global request modifications
    "django.middleware.csrf.CsrfViewMiddleware",  # ✅ Protects against CSRF attacks
    "django.contrib.auth.middleware.AuthenticationMiddleware",  # ✅ Ensures user authentication
    "django.contrib.messages.middleware.MessageMiddleware",  # ✅ Handles Django's messaging framework
    "django.middleware.clickjacking.XFrameOptionsMiddleware",  # ✅ Prevents clickjacking attacks
    "csp.middleware.CSPMiddleware",  # ✅ Add this line to enforce CSP
]


# Default message storage
from django.contrib.messages import constants as messages

MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"


ROOT_URLCONF = "LPageToAdmin.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],  # ✅ Use this for project-level templates
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "LPageToAdmin.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Check if running on Heroku (Heroku sets the DATABASE_URL environment variable)
if "DATABASE_URL" in os.environ:
    DATABASES = {
        "default": dj_database_url.config(conn_max_age=600, ssl_require=True)
    }
else:
    print("⚠️ Using SQLite for local development")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# Static files (CSS, JavaScript, Images)
# URL to serve static files
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # For production use
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "/useradmin/"  # Redirect to the Admin Dashboard
LOGOUT_REDIRECT_URL = "/accounts/login/"  # Redirect users to login page after logout

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django.template": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
    },
}

# ✅ Correct CSRF settings
CSRF_USE_SESSIONS = True  # ✅ Store CSRF token in session instead of cookies
CSRF_FAILURE_VIEW = "app.views.csrf_failure"  # ✅ Ensure this view exists

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Add this at the bottom of settings.py
CORS_ALLOW_ALL_ORIGINS = False  # ✅ Set to False for security
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8000",  # Local development
    "https://windowgeniusai.herokuapp.com",  # Production on Heroku
    "https://windowgeniusai-d6c9fb157af2.herokuapp.com",  # Temporary Heroku domain
    "https://www.windowgeniusai.com",  # Custom domain (if set up)
    "https://windowgeniusai.com",  # Your actual deployed domain
]

CORS_ALLOW_CREDENTIALS = True  # ✅ Allow cookies & authentication if needed

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",  # Local
    "https://windowgeniusai.herokuapp.com",  # Heroku
    "https://windowgeniusai-d6c9fb157af2.herokuapp.com",  # Temporary domain
    "https://www.windowgeniusai.com",  # Custom domain
    "https://windowgeniusai.com",  # Main domain
]

CSRF_COOKIE_NAME = "csrftoken"  # ✅ Set CSRF cookie name
CSRF_COOKIE_SECURE = False  # ✅ Set to True in production (only if using HTTPS)
CSRF_COOKIE_HTTPONLY = False  # ✅ Allows JavaScript to read CSRF cookie
CSRF_USE_SESSIONS = False  # ✅ Make sure CSRF is stored in cookies (not sessions)


# ✅ Content Security Policy (CSP) Fixes
CSP_DEFAULT_SRC = ("'self'", "https://windowgeniusai.herokuapp.com", "https://windowgeniusai.com")

CSP_SCRIPT_SRC = (
    "'self'",
    "https://cdn.jsdelivr.net",  # ✅ External JS (Bootstrap, jQuery, etc.)
    "https://cdnjs.cloudflare.com",  # ✅ Cloudflare scripts
    "https://code.jquery.com",  # ✅ jQuery CDN
    "https://www.googletagmanager.com",  # ✅ Google Analytics / Tag Manager
    "'unsafe-inline'",  # ✅ Allows inline JS (only for debugging, remove in production)
)

CSP_FONT_SRC = (
    "'self'",
    "https://fonts.googleapis.com",
    "https://fonts.gstatic.com",
    "https://cdnjs.cloudflare.com",
    "https://cdn.jsdelivr.net",
)

CSP_STYLE_SRC = (
    "'self'",
    "https://fonts.googleapis.com",
    "https://cdn.jsdelivr.net",
    "https://cdnjs.cloudflare.com",
    "'unsafe-inline'",  # ✅ Allows inline styles (needed for Bootstrap & Google Fonts)
)

CSP_CONNECT_SRC = (
    "'self'",
    "https://windowgeniusai.herokuapp.com",
    "https://windowgeniusai.com",
    "https://api.openai.com",  # ✅ If using OpenAI API
)

CSP_IMG_SRC = (
    "'self'",
    "data:",
    "https://windowgeniusai.herokuapp.com",
    "https://windowgeniusai.com",
    "https://cdn.jsdelivr.net",
    "https://fonts.gstatic.com",
)

# Import django-heroku at the bottom
import django_heroku

# Apply Heroku settings
django_heroku.settings(locals())

# Database settings for Heroku
import dj_database_url
DATABASES["default"] = dj_database_url.config(conn_max_age=600, ssl_require=True)
