name: Deploy to AWS ECS

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ecs-deploy
  cancel-in-progress: true

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 629965575535.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: windowgeniusai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::629965575535:role/github-actions-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

          docker buildx build --platform linux/amd64 -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Install CDK dependencies
        run: |
          cd cdk-windowgeniusai
          pip install -r requirements.txt

      - name: CDK deploy
        run: |
          set -euo pipefail
          cdk synth --app "python3 cdk-windowgeniusai/app.py" -c imageTag=$IMAGE_TAG
          cdk deploy \
            --require-approval never \
            --app "python3 cdk-windowgeniusai/app.py" \
            -c imageTag=$IMAGE_TAG
